apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: uber-data
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: uber-data
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/TanzuDK/uber-data.git
      ref:
        branch: main
