apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: python-accelerator
  name: python-accelerator
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: python-accelerator
  sessionAffinity: None
  type: NodePort
